---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: luna-key-broker-for-dke
  name: luna-key-broker-for-dke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luna-key-broker-for-dke
  strategy: {}
  template:
    metadata:
      labels:
        app: luna-key-broker-for-dke
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - image: YOUR_ACR_RESOURCE.azurecr.io/luna-key-broker-for-dke-centos7:v1.2.0
          name: luna-key-broker-for-dke
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: luna-config
              mountPath: /usr/safenet/lunaclient/config/
            - name: rego-file
              mountPath: /usr/safenet/lunaclient/rego/
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "5000"
            - name: P11_LIB
              value: /usr/safenet/lunaclient/libs/64/libCryptoki2_64.so
            - name: P11_TOKEN
              value: lkb-hsm
            - name: USER_TYPE
              value: "2"
            - name: CACHING_ENABLED
              value: "true"
            - name: CACHING_HOURS
              value: "1"
            - name: JWT_AUDIENCE
              value: "https://YOUR_DKE_SERVICE_FQDN"
            - name: JWT_ISSUER
              value: "https://sts.windows.net/YOUR_TENANT_ID/"
            - name: JWT_JWKS
              value: https://login.windows.net/common/discovery/keys
            - name: P11_PIN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
            - name: REGO_FILE
              value: /usr/safenet/lunaclient/rego/opa_policies.rego
      volumes:
        - name: luna-config
          secret:
            secretName: luna-config-file
        - name: rego-file
          secret:
            secretName: auth-claim

---
apiVersion: v1
kind: Service
metadata:
  name: luna-key-broker-for-dke
spec:
  type: NodePort
  selector:
    app: luna-key-broker-for-dke
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
